services:
  was01:
    build: ./springboot_was
    ports:
      - "8081:8080"
    volumes:
      - ./app_images:/upload/images

  was02:
    build: ./springboot_was
    ports:
      - "8082:8080"
    volumes:
      - ./app_images:/upload/images

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/etcNginx/nginx.conf:/etc/nginx/nginx.conf
      - D:\dockerTest\compose\03\webServer\etcNginx\conf.d\default.conf:/etc/nginx/conf.d/default.conf
      - D:\dockerTest\compose\03\webServer\varCacheNginx:/asdcache